name: csslib_test_suite
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/csslib-test-suite
description: CSS parsing test suite (originated from W3C).
version: 0.9.0
dependencies:
  csslib: any
  html5lib: any
dev_dependencies:
  unittest: ^0.11.0
environment:
  sdk: ">=1.0.0 <2.0.0"
