name: csslib_test_suite
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/csslib-test-suite
description: CSS parsing test suite (originated from W3C).
version: 0.8.10
dependencies:
  csslib: any
  html5lib: any
dev_dependencies:
  unittest: any
environment:
  sdk: ">=0.8.10"
